### ISSUE TITLE
Lossy variants of from/toWtf8Array

### ISSUE THREAD

**Issue by vouillon** [WebAssembly/js-string-builtins#11]
For a language like OCaml, where string are arrays of bytes with no enforced encoding, it makes a lot of sense to replace invalid sequences by U+FFFD instead of trapping. This is the semantics provided by TextEncoder / TextDecoder.

**Comment by eqrion** [comment]
I believe this is now fixed with the introduction of the text-encoder/text-decoder namespaces.
