### ISSUE TITLE
Naming inconsistency: "concat" vs. "concatenate"

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/js-string-builtins#12]
It is my understanding that this proposal intentionally uses the existing JavaScript names of the various operations (e.g. `charCodeAt` instead of `getCodeunit`), to illustrate that no new capabilities are being added to the web platform.

The name `"wasm:js-string" "concatenate"` is not in line with this principle. Presumably this should be renamed to `"concat"`, to match [`String.prototype.concat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat)?

**Comment by eqrion** [comment]
Good catch. I missed that there was a concat method, I thought there was only a `+` operator. Will rename.
