### ISSUE TITLE
Streaming-related functions need to be updated too

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/js-string-builtins#16]
The overview currently doesn't mention `WebAssembly.compileStreaming` and `WebAssembly.instantiateStreaming`. Since these two can also trigger compilation, they should also get the new `options` parameter; otherwise users of the streaming API would be unable to use builtin modules.

**Comment by eqrion** [comment]
Good catch, filed a PR for it.

**Comment by eqrion** [comment]
This was fixed in #20.
