### ISSUE TITLE
The section "Encoding API" still uses immutable `array i8`

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/js-string-builtins#19]
Looks like these occurrences were forgotten in the recent switch to mutable arrays everywhere:

- The internal [module definition](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#encoding-api) contains `(type $array_i8 (array i8))` and `(func (export "array_i8_get") ...`
- [decodeStringFromUTF8Array](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#wasmtext-decoder-decodestringfromutf8array) takes a parameter of type `$array_i8`, and calls the function `array_i8_get` on it

We should just use `(type $array_i8_mut (array (mut i8)))` everywhere (and could then optionally drop the `_mut` suffix from its name for brevity).

**Comment by eqrion** [comment]
Good catch, file a PR for this.
