### ISSUE TITLE
question about feature detection

### ISSUE THREAD

**Issue by tlively** [WebAssembly/js-string-builtins#22]
I'm not sure how feature detection as [currently described](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#feature-detection) in the overview is supposed to work. If I pass the extra builtin options to `WebAssembly.validate()` on an engine that supports them, I would expect it to return `true` (assuming my module is valid and has no builtin link errors). But if my module is valid and has no link errors, then it will also be valid on an engine that does not support builtins.

Is the idea that one should call `validate` with a module that will produce builtin link errors instead?

**Comment by jakobkummerow** [comment]
Using validation _failure_ as feature presence indicator is certainly what I've been suggesting to folks.

The smallest snippet I've come up with so far is:
```
function DetectImportedStrings() {
 let bytes = [
   0,   97,  115, 109, 1,   0,   0,  0,   1,   4,   1,   96,  0,
   0,   2,   23,  1,   14,  119, 97, 115, 109, 58,  106, 115, 45,
   115, 116, 114, 105, 110, 103, 4,  99,  97,  115, 116, 0,   0
 ];
 return !WebAssembly.validate(
     new Uint8Array(bytes), {builtins: ['js-string']});
}
```
Explanation:
```
[
  0x00, 0x61, 0x73, 0x6d,  // wasm magic
  0x01, 0x00, 0x00, 0x00,  // wasm version

  0x01,                    // section kind: Type
  0x04,                    // section length 4
  0x01, 0x60,              // types count 1:  kind: func
  0x00,                    // param count 0
  0x00,                    // return count 0

  0x02,                    // section kind: Import
  0x17,                    // section length 23
  0x01,                    // imports count 1: import #0
  0x0e,                    // module name length: 14
  0x77, 0x61, 0x73, 0x6d, 0x3a, 0x6a, 0x73, 0x2d,
  0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
                           // module name: wasm:js-string
  0x04,                    // field name length: 4
  0x63, 0x61, 0x73, 0x74,  // field name: cast
  0x00, 0x00,              // kind: function, with signature #0
]
```

**Comment by tlively** [comment]
Thanks, that makes sense. I uploaded a PR clarifying this in the overview: https://github.com/WebAssembly/js-string-builtins/pull/23

**Comment by eqrion** [comment]
To be honest, I didn't think through this and didn't realize that you'd need to deliberately create link errors to discover if there are builtins enabled. It's a bit odd, but I guess it works? I'm open to other suggestions.

The nice part of using validate (as opposed to a `WebAssembly.hasBuiltinModule(x)`, which is what was here before) was that it would allow you to check for the presence of a specific builtin within a collection, which would allow us to add more later.

**Comment by tlively** [comment]
Closing this since the overview was updated with more details.
