### ISSUE TITLE
Web Platform Tests

### ISSUE THREAD

**Issue by ecmziegler** [WebAssembly/js-string-builtins#33]
Are there any plans on adding Web Platform Tests for this proposal? Because it defines a JS-observable behavior, it might make sense to add these like we did for other proposals in the past. At least we could add a test to check if `WebAssembly.instantiate()` succeeds or fails when called on a module which uses the implicit function/constants imports and if the exposed objects have the correct types.

Adding functional tests for the implicit functions and if they do the right thing might not be necessary, because this should be well covered by Wasm tests.

**Comment by eqrion** [comment]
I did add tests locally to this [repo](https://github.com/WebAssembly/js-string-builtins/tree/main/test/js-api/js-string). It'd probably be good to get that in WPT.

**Comment by eqrion** [comment]
I added two more tests into this repo, and then I'm landing a [commit](https://bugzilla.mozilla.org/show_bug.cgi?id=1912523) which will get all of these tests into WPT.
