### ISSUE TITLE
Shall we validate builtin set names?

### ISSUE THREAD

**Issue by vouillon** [WebAssembly/js-string-builtins#40]
I'm wondering whether the builtin set names should be validated, as specified here:
https://github.com/WebAssembly/js-string-builtins/blob/a3c7562be0c8fbe9dd6d289360e6fa26ed3b29cc/document/js-api/index.bs#L1754-L1759

An advantage is that for [feature detection](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#feature-detection) one doesn't even need to import a builtin operation with an incorrect signature.

But it makes progressive enhancement more complicated. The current [progressive enhancement](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#progressive-enhancement) section states that it's safe for users to request builtins while still providing a polyfill for backup behavior and the optimal path will be chosen. But if we validate the builtin set names and some builtins are not supported, the validation is going to fail even when a polyfill is provided.

**Comment by eqrion** [comment]
Ah, I had only thought about the case of an engine implementing this proposal vs not implementing this proposal. I didn't think through progressive enhancement for the case of future builtin proposals.

I agree that not validating the builtin set names would make progressive enhancement simpler. I can't think of any downsides right now, so it seems like a good improvement to make.

**Comment by eqrion** [comment]
This should be fixed by 7851a7832b14ec0ddb5103fb003dddaec89df13f.
