### ISSUE TITLE
Question: Does the compile-time import mechanism opens up possibilities of other "JS Builtin" APIs?

### ISSUE THREAD

**Issue by igrep** [WebAssembly/js-string-builtins#42]
If I understand correctly, this proposal consists of two changes:

- (A) Mechanism to import functions predefined by the host at compile time so that the host can optimize better.
- (B) APIs compatible with String in JavaScript assumed to use in browsers via (A).

Now, I'm curious if (A) is actually available for other "JS Builtin" APIs other than String, such as RegExp, Map, DOM etc. Do you plan or hope to define them in the future?

**Comment by tlively** [comment]
Yes, we've discussed using this pattern for more APIs in the future. Some APIs make more sense to provide as builtins than others, though. String operations are so fast and performance-sensitive that the overhead of calling out to JS to perform the operations is significant and worth removing. For more complex APIs like the DOM, the overhead of calling out to JS is probably much less significant, so there would be much less benefit to providing them as builtins.

**Comment by igrep** [comment]
Thank you! I got it.
